"""Builds the self-hosted woff2 fonts in src/fonts from pinned google/fonts sources.

Usage: python scripts/fonts/build-fonts.py <dir-with-ttf-sources>
Requires: fonttools[woff] (fonttools + brotli).

Sources: https://github.com/google/fonts at commit 9710da1eacb3be272583c3224dcb70f9da6eadbb
  ofl/baloobhaijaan2/BalooBhaijaan2[wght].ttf
  ofl/amiri/Amiri-{Regular,Bold}.ttf
  ofl/ibmplexsansarabic/IBMPlexSansArabic-{Regular,Medium,Bold}.ttf
Each font is subset to its family's ranges in src/fonts/unicode-ranges.json (the
shared "core" plus the family's "extra" ranges, if any), keeping every OpenType
layout feature so Arabic shaping, marks and ligatures are unchanged. The build
then writes src/fonts/cmap.json: the SHA-256 of each shipped file and the code
points it maps. src/lib/athkar/font-coverage.test.ts checks every character the
site renders against those code points, and the files against those hashes.

IBM Plex Sans Arabic is licensed with Reserved Font Name "Plex". A subset is a
Modified Version under the OFL, so its user-facing names (name IDs 1, 3, 4, 6,
16, 18, 21) are renamed to "Athkar Sans Arabic". Copyright, trademark and
license records are kept unchanged. The build fails if a reserved name remains.
"""

import hashlib
import json
import sys
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "src" / "fonts"
FONTS = {
    "BalooBhaijaan2[wght].ttf": "BalooBhaijaan2-Variable.woff2",
    "Amiri-Regular.ttf": "Amiri-Regular.woff2",
    "Amiri-Bold.ttf": "Amiri-Bold.woff2",
    "IBMPlexSansArabic-Regular.ttf": "AthkarSansArabic-Regular.woff2",
    "IBMPlexSansArabic-Medium.ttf": "AthkarSansArabic-Medium.woff2",
    "IBMPlexSansArabic-Bold.ttf": "AthkarSansArabic-Bold.woff2",
}

# OFL Reserved Font Names that must not appear in Modified Versions' names.
RESERVED = {"IBMPlexSansArabic": "Plex"}
RENAMES = [("IBM Plex Sans Arabic", "Athkar Sans Arabic"), ("IBMPlexSansArabic", "AthkarSansArabic")]
NAME_IDS = {1, 3, 4, 6, 16, 18, 21}

CMAP_COMMENT = (
    "Generated by scripts/fonts/build-fonts.py; do not edit. For each shipped font: its SHA-256 "
    "and the code points it maps. src/lib/athkar/font-coverage.test.ts checks the site's text against them."
)


def parse_ranges(ranges: list[str]) -> set[int]:
    points: set[int] = set()
    for r in ranges:
        lo, _, hi = r.removeprefix("U+").partition("-")
        points.update(range(int(lo, 16), int(hi or lo, 16) + 1))
    return points


def format_ranges(points: set[int]) -> list[str]:
    """Code points as sorted "U+XXXX" / "U+XXXX-YYYY" ranges."""
    out: list[str] = []
    ordered = sorted(points)
    start = prev = ordered[0]
    for cp in [*ordered[1:], None]:
        if cp is not None and cp == prev + 1:
            prev = cp
            continue
        out.append(f"U+{start:04X}" if start == prev else f"U+{start:04X}-{prev:04X}")
        if cp is not None:
            start = prev = cp
    return out


def family_codepoints(family: str) -> set[int]:
    """The shared core ranges plus this family's extra ranges."""
    spec = json.loads((OUT / "unicode-ranges.json").read_text(encoding="utf-8"))
    return parse_ranges(spec["core"]) | parse_ranges(spec["extra"].get(family, []))


def rename_reserved(font: TTFont, reserved: str) -> None:
    """Rename user-facing name records of a Modified Version; keep legal records."""
    for record in font["name"].names:
        if record.nameID not in NAME_IDS:
            continue
        text = record.toUnicode()
        for old, new in RENAMES:
            text = text.replace(old, new)
        if reserved in text:
            raise SystemExit(f"reserved name {reserved!r} left in name ID {record.nameID}: {text!r}")
        record.string = text


def main() -> None:
    src = Path(sys.argv[1])
    options = subset.Options()
    options.flavor = "woff2"
    options.layout_features = ["*"]
    options.name_IDs = ["*"]
    options.name_languages = ["*"]
    options.notdef_outline = True
    options.glyph_names = False
    shipped: dict[str, dict[str, object]] = {}
    for ttf, woff2 in FONTS.items():
        font = TTFont(src / ttf)
        keep = family_codepoints(woff2.split("-")[0])
        subsetter = subset.Subsetter(options)
        subsetter.populate(unicodes=sorted(keep & set(font.getBestCmap())))
        subsetter.subset(font)
        for prefix, reserved in RESERVED.items():
            if ttf.startswith(prefix):
                rename_reserved(font, reserved)
        font.flavor = "woff2"
        path = OUT / woff2
        font.save(path)
        shipped[woff2] = {
            "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
            "cmap": format_ranges(set(font.getBestCmap())),
        }
        print(f"{woff2:36} {path.stat().st_size / 1024:6.1f} KB")
    cmap = {"_comment": CMAP_COMMENT, "fonts": dict(sorted(shipped.items()))}
    (OUT / "cmap.json").write_text(json.dumps(cmap, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
